### PR TITLE
Add support for adding custom fonts to Chromium

### PR DESCRIPTION
**Pull request by Loots-it**
As discussed in: https://github.com/stefanzweifel/sidecar-browsershot/issues/97

### CODE REVIEW

**Comment by Loots-it** [comment]
This should be fully backwards compatible, they can configure which resource path they use for the font directory with the config: font_resource_path. All the fonts in this directory will be loaded into the lambda function. I added a test which compares the generated jpg with the reference jpg in this project. I wanted to add one for pdf too, but for some reason the comparison of pdfs isn't that easy...

**Comment by Loots-it** [comment]
I was just playing around with the pdf reference file, the problem is that the metadata isn't exactly the same... I'm trying to get this working...

**Comment by Loots-it** [comment]
I just added the .pdf reference test. I just changed the creationdate and moddate metadata and compare the result with the reference... I have never worked with pest tests, so if you have any recommendations on how to clean up that part of the code, I'm all ears.

**Comment by stefanzweifel** [comment]
Thanks @Loots-it. Adding a test that compares PDFs is no small feat. Will take a closer look.

**Comment by stefanzweifel** [comment]
@Loots-it I've just pushed some changes to this PR. I've simplified the naming a bit and called the config now just `fonts`. I've also reworked, how the fonts are read/discovered from the file system (method returns an array).

Even contemplated with myself, if we should put the entire "font-declaration" into the config. Something like this:

```php
/**
 * Define custom fonts to include.
 */
'fonts' => [
    __DIR__ . '/../../resources/lambda/fonts/NotoColorEmoji.ttf' => 'fonts/NotoColorEmoji.ttf'
    resource_path('sidecar-browsershot/fonts/ComicSans.ttf') => 'fonts/ComicSans.ttf'
],
```

Do you think that would make it easier for folks to add new fonts? Adding tons of fonts would probably be a bit more cumbersome, but I hope people don't add 50 fonts to their Lambda functions. :)

Also updated the README with a bit of documentation.

If its all right for you, I will probably merge this PR and tag a new release in the next few days.

**Comment by Loots-it** [comment]
@stefanzweifel, thanks for the effort! By going through your changes I discovered that I made a mistake with the configuration, which you fixed, thanks! I also thought about putting the whole font config in the configuration file like you suggested. But I think it would be more work to add a new font this way. There would also be a lot of redundant information in the config file, which I don't like. The font file name is repeated, the fonts directory is repeated on every line, and the path of the font dir is probably also repeated on each line.

But either way works for me, it would just be awesome if custom font support can be added one way or another :)

I have one little remark on your changes. You add the emoji font by default, even if the user adds their own fonts, personally I think it's odd that we always have to include the emoji font, even if we don't want to use it... There are a lot of use case where emojis are never used. But that's just my opinion of course :)

**Comment by stefanzweifel** [comment]
I agree, adding each font directly into the config is quite noisy. Let's go forward with the current approach.

> You add the emoji font by default, even if the user adds their own fonts, personally I think it's odd that we always have to include the emoji font, even if we don't want to use it... There are a lot of use case where emojis are never used.

I will keep the emoji font by default, even if a user adds thei own fonts to the package.
In the past, we had a couple off issues/discussions around this. Many users expect emojis to work out-of-the-box.

By adding the font automatically, we prevent potential issues automatically.

Will merge and tag a new release shortly.

**Pull request merged**
