### PR TITLE
Include emoji font in lambda bundle

### PR DESCRIPTION
**Pull request by Admiral-Enigma**
Related to #50 

I have not had the chance to test yet.

### CODE REVIEW

**Comment by Admiral-Enigma** [comment]
@stefanzweifel Seems like the actions might be missing some AWS config envs to work properly?

**Comment by stefanzweifel** [comment]
@Admiral-Enigma Yeah, I still need to figure out how to pass the repo secrets to the GitHub Action to work for pull_requests. Will test the PR tonight on my local machine.

**Comment by stefanzweifel** [comment]
Thanks again for the PR. 🙌

The path to the font in `chromium.font()` needs to be absolute. After reading through [this repository](https://github.com/Sparticuz/chromium#fonts) I figured out that the base structure on Lambda is `/var/task/`.

I've also removed the font-file from the repo itself and added a `beforeDeployment`-hook to the Sidecar function, to download the file once before the first deployment.

Thought process behind this, is that I don't want to maintain an up-to-date copy of the emoji font in the repo. Let users download that the newest version when they deploy the function.

@Admiral-Enigma Do you think that would work for your project as well?

---

CI tests still fail, as the PR doesn't seem to have access to the secrets. Local tests after successful deployment to Lambda are all green.

**Comment by stefanzweifel** [comment]
@Admiral-Enigma Right. When you run `php artisan sidecar:deploy` the font is fetched from GitHub and embedded in the zip that is stored in the S3 bucket.

Then I will merge and tag a new version soon.

**Pull request merged**
